package("collab-process")
    set_homepage("https://github.com/BuildWithCollab/collab-process")
    set_description("Collab Process ▶️🖥️")
    set_license("0BSD")
    add_urls("https://github.com/BuildWithCollab/collab-process/archive/refs/tags/$(version).tar.gz")
    add_versions("v0.1.0", "6dcf3892cfa577fe8c0a8b1cc6cce18c9826806de849bc16c294ff120c0623bc")
    add_deps("collab-core")
    add_deps("fmt")
    on_install(function (package)
        import("package.tools.xmake").install(package, { build_tests = false })
    end)
